[package]
name = "logru"
version = "0.1.0"
authors = ["Fabian Thorand <f.thorand@gmail.com>"]
edition = "2018"

[dependencies]
tracing = "0.1.29"
logos = "0.12.0"

[dev-dependencies]
criterion = "0.3.5"
tracing-subscriber = "0.2.25"

[profile.release]
debug = true

[[bench]]
name = "criterion"
harness = false