name: Build and test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: fatho
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix --extra-experimental-features nix-command build --print-build-logs --keep-going --file default.nix
      - run: nix-shell --run "echo OK"